### ISSUE TITLE
大佬，能再提供一些自动控制原理的相关资料吗？

### ISSUE THREAD

**Issue by Xuxuduoyu** [HelinXu/THUDA-9#1]
本人就读于buaa，想参加清华自动化的推免考试，希望大佬再能提供一些自控原理的资料。我已fork+star

**Comment by HelinXu** [comment]
hi 不好意思，我不太了解推免考试的情况，所以给不出具体的建议，也不太清楚哪些参考资料会比较有效。或许可以看看我们学校的学堂在线和教材？

**Comment by Xuxuduoyu** [comment]
> hi 不好意思，我不太了解推免考试的情况，所以给不出具体的建议，也不太清楚哪些参考资料会比较有效。或许可以看看我们学校的学堂在线和教材？

好的好的，谢谢

**Comment by HelinXu** [comment]
不客气，祝好运！
